# Generated by Django 5.0.3 on 2024-03-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
        model_name='employee',
        name='position',
        field=models.CharField(default='', max_length=100),
        preserve_default=False,
    ),
    ]
