# Generated by Django 5.0.2 on 2024-06-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='address',
        ),
        migrations.RemoveField(
            model_name='record',
            name='city',
        ),
        migrations.RemoveField(
            model_name='record',
            name='country',
        ),
        migrations.RemoveField(
            model_name='record',
            name='province',
        ),
    ]
